name: 'react_bootstrap_demo'
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  react: "^0.7.1"
  react_bootstrap:
    path: ../react_bootstrap
